RapidProto2/RapidProto2/Models/ErrorViewModel.cs
using System;

namespace RapidProto2.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

RapidProto2/RapidProto2/Models/VirtualAccount.cs
using System;
using System.Collections.Generic;

namespace RapidProto2.Models
{
    public class VirtualAccount
    {
        public int ID { get; set; }
        public int virtualmoney { get; set; }
        public int bitcoin { get; set; }
        public int ethereum { get; set; }
    }
}

RapidProto2/RapidProto2/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using RapidProto2.Models;

namespace RapidProto2.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult About()
        {
            ViewData["Message"] = "Your application description page.";

            return View();
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }

        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

RapidProto2/RapidProto2/Controllers/VirtualAccountsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using RapidProto2.Data;
using RapidProto2.Models;

namespace RapidProto2.Controllers
{
    public class VirtualAccountsController : Controller
    {
        private readonly InvestmentContext _context;

        public VirtualAccountsController(InvestmentContext context)
        {
            _context = context;
        }

        // GET: VirtualAccounts
        public async Task<IActionResult> Index()
        {
            return View(await _context.VirtualAccounts.ToListAsync());
        }

        // GET: VirtualAccounts/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var virtualAccount = await _context.VirtualAccounts
                .SingleOrDefaultAsync(m => m.ID == id);
            if (virtualAccount == null)
            {
                return NotFound();
            }

            return View(virtualAccount);
        }

        // GET: VirtualAccounts/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: VirtualAccounts/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ID,virtualmoney,bitcoin,ethereum")] VirtualAccount virtualAccount)
        {
            if (ModelState.IsValid)
            {
                _context.Add(virtualAccount);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(virtualAccount);
        }

        // GET: VirtualAccounts/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var virtualAccount = await _context.VirtualAccounts.SingleOrDefaultAsync(m => m.ID == id);
            if (virtualAccount == null)
            {
                return NotFound();
            }
            return View(virtualAccount);
        }

        // POST: VirtualAccounts/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ID,virtualmoney,bitcoin,ethereum")] VirtualAccount virtualAccount)
        {
            if (id != virtualAccount.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(virtualAccount);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!VirtualAccountExists(virtualAccount.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(virtualAccount);
        }

        // GET: VirtualAccounts/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var virtualAccount = await _context.VirtualAccounts
                .SingleOrDefaultAsync(m => m.ID == id);
            if (virtualAccount == null)
            {
                return NotFound();
            }

            return View(virtualAccount);
        }

        // POST: VirtualAccounts/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var virtualAccount = await _context.VirtualAccounts.SingleOrDefaultAsync(m => m.ID == id);
            _context.VirtualAccounts.Remove(virtualAccount);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool VirtualAccountExists(int id)
        {
            return _context.VirtualAccounts.Any(e => e.ID == id);
        }
    }
}

RapidProto2/RapidProto2/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - RapidProto2</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">RapidProto2</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="About">About</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Contact">Contact</a></li>
                    <li><a asp-area="" asp-controller="VirtualAccounts" asp-action="Index">Virtual Account</a></li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2017 - RapidProto2</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>

RapidProto2/RapidProto2/Views/VirtualAccounts/Create.cshtml
@model RapidProto2.Models.VirtualAccount

@{
    ViewData["Title"] = "Create";
}

<h2>Create</h2>

<h4>VirtualAccount</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="virtualmoney" class="control-label"></label>
                <input asp-for="virtualmoney" class="form-control" />
                <span asp-validation-for="virtualmoney" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="bitcoin" class="control-label"></label>
                <input asp-for="bitcoin" class="form-control" />
                <span asp-validation-for="bitcoin" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ethereum" class="control-label"></label>
                <input asp-for="ethereum" class="form-control" />
                <span asp-validation-for="ethereum" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

RapidProto2/RapidProto2/Views/VirtualAccounts/Delete.cshtml
@model RapidProto2.Models.VirtualAccount

@{
    ViewData["Title"] = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>VirtualAccount</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.virtualmoney)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.virtualmoney)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.bitcoin)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.bitcoin)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.ethereum)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ethereum)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="ID" />
        <input type="submit" value="Delete" class="btn btn-default" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

RapidProto2/RapidProto2/Views/VirtualAccounts/Details.cshtml
@model RapidProto2.Models.VirtualAccount

@{
    ViewData["Title"] = "Details";
}

<h2>Details</h2>

<div>
    <h4>VirtualAccount</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.virtualmoney)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.virtualmoney)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.bitcoin)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.bitcoin)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.ethereum)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ethereum)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.ID">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

RapidProto2/RapidProto2/Views/VirtualAccounts/Edit.cshtml
@model RapidProto2.Models.VirtualAccount

@{
    ViewData["Title"] = "Edit";
}

<h2>Edit</h2>

<h4>VirtualAccount</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="ID" />
            <div class="form-group">
                <label asp-for="virtualmoney" class="control-label"></label>
                <input asp-for="virtualmoney" class="form-control" />
                <span asp-validation-for="virtualmoney" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="bitcoin" class="control-label"></label>
                <input asp-for="bitcoin" class="form-control" />
                <span asp-validation-for="bitcoin" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ethereum" class="control-label"></label>
                <input asp-for="ethereum" class="form-control" />
                <span asp-validation-for="ethereum" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

RapidProto2/RapidProto2/Views/VirtualAccounts/Index.cshtml
@model IEnumerable<RapidProto2.Models.VirtualAccount>

@{
    ViewData["Title"] = "Index";
}

<h2>Index</h2>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
                <th>
                    @Html.DisplayNameFor(model => model.virtualmoney)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.bitcoin)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.ethereum)
                </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.virtualmoney)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.bitcoin)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ethereum)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.ID">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.ID">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.ID">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>